from fpdf import FPDF
import tempfile
import os

class SafePDF(FPDF):
    def cell(self, w, h=0, txt="", border=0, ln=0, align="", fill=False, link=""):
        safe_txt = str(txt).encode("latin-1", "replace").decode("latin-1")
        super().cell(w, h, safe_txt, border, ln, align, fill, link)
        
    def multi_cell(self, w, h, txt, border=0, align="J", fill=False):
        safe_txt = str(txt).encode("latin-1", "replace").decode("latin-1")
        super().multi_cell(w, h, safe_txt, border, align, fill)

def generate_audit_memo(project_data: dict, risk_data: dict) -> str:
    pdf = SafePDF(unit="mm", format="A4")
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "CAG-Oriented Audit Memo", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 5, "(Generated by Agent Kautilya - Backend Service)", ln=True, align="C")
    pdf.ln(10)
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Project ID: {project_data.get('project_id')}", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Work Name: {project_data.get('work_type')}", ln=True)
    pdf.cell(0, 6, f"MP Name: {project_data.get('mp_name')}", ln=True)
    pdf.cell(0, 6, f"Vendor: {project_data.get('vendor')}", ln=True)
    pdf.cell(0, 6, f"Sanctioned Amount: INR {project_data.get('sanctioned_amount', 0):,.2f}", ln=True)
    pdf.ln(5)
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Risk Assessment", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Risk Score: {risk_data.get('risk_score')}", ln=True)
    pdf.cell(0, 6, f"Risk Level: {risk_data.get('risk_level')}", ln=True)
    pdf.cell(0, 6, f"ML Probability: {risk_data.get('ml_probability')}", ln=True)
    pdf.cell(0, 6, f"Rule Signal: {risk_data.get('rule_signal')}", ln=True)
    
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 6, "Triggered Rules:", ln=True)
    pdf.set_font("Helvetica", "", 11)
    rules = risk_data.get('rules', {}).get('triggered_rules', [])
    if rules:
        for r in rules:
            pdf.cell(0, 6, f"- {r}", ln=True)
    else:
        pdf.cell(0, 6, "None", ln=True)
        
    pdf.ln(15)
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(0, 5, "Disclaimer: This is an AI-generated anomaly report intended for internal auditor guidance. It does not constitute legal proof of fraud.")
    
    fd, path = tempfile.mkstemp(suffix=".pdf")
    os.close(fd)
    pdf.output(path)
    return path
